# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotableapp', '0001_initial'),
        ('favoritesapp', '0001_initial'),
        ('logregapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='fav_quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_quotes', to='quotableapp.Quote'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user_favoriting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_fav', to='logregapp.User'),
        ),
    ]
